package defpackage;

import java.util.HashMap;
import org.apache.http.HttpStatus;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes2.dex */
public final class sla {
    public static final sla A0;
    public static final sla A1;
    public static final sla B0;
    public static final sla B1;
    public static final sla C0;
    public static final sla C1;
    public static final sla D0;
    public static final sla D1;
    public static final sla E0;
    public static final sla E1;
    public static final sla F0;
    public static final sla F1;
    public static final sla G0;
    public static final sla G1;
    public static final sla H0;
    public static final sla H1;
    public static final sla I0;
    public static final sla I1;
    public static final sla J0;
    public static final sla J1;
    public static final sla K0;
    public static final sla K1;
    public static final sla L0;
    public static final sla L1;
    public static final sla M0;
    public static final sla M1;
    public static final sla N0;
    public static final sla N1;
    public static final sla O0;
    public static final sla O1;
    public static final sla P0;
    public static final sla P1;
    public static final sla Q0;
    public static final sla Q1;
    public static final sla R0;
    public static final sla R1;
    public static final sla S0;
    public static final sla S1;
    public static final sla T0;
    public static final sla T1;
    public static final sla U0;
    public static final sla U1;
    public static final sla V0;
    public static final sla V1;
    public static final sla W0;
    public static final sla W1;
    public static final sla X;
    public static final sla X0;
    public static final sla X1;
    public static final sla Y;
    public static final sla Y0;
    public static final sla Y1;
    public static final sla Z;
    public static final sla Z0;
    public static final sla Z1;
    public static final sla a1;
    public static final sla a2;
    public static final sla b1;
    public static final sla b2;
    public static final yb9 c;
    public static final sla c1;
    public static final sla c2;
    public static final sla d1;
    public static final sla d2;
    public static final sla e1;
    public static final sla e2;
    public static final sla f1;
    public static final sla f2;
    public static final sla g1;
    public static final sla g2;
    public static final sla h1;
    public static final sla h2;
    public static final sla i1;
    public static final sla i2;
    public static final sla j1;
    public static final sla j2;
    public static final sla k1;
    public static final sla k2;
    public static final sla l1;
    public static final sla l2;
    public static final sla m1;
    public static final sla m2;
    public static final sla n1;
    public static final sla n2;
    public static final HashMap o;
    public static final sla o1;
    public static final sla o2;
    public static final sla p1;
    public static final sla p2;
    public static final sla q1;
    public static final /* synthetic */ sla[] q2;
    public static final sla r1;
    public static final sla s0;
    public static final sla s1;
    public static final sla t0;
    public static final sla t1;
    public static final sla u0;
    public static final sla u1;
    public static final sla v0;
    public static final sla v1;
    public static final sla w0;
    public static final sla w1;
    public static final sla x0;
    public static final sla x1;
    public static final sla y0;
    public static final sla y1;
    public static final sla z0;
    public static final sla z1;
    public final short a;
    public final s43 b;

    static {
        sla slaVar = new sla("PING", 0, (short) 1, null);
        sla slaVar2 = new sla("DEBUG", 1, (short) 2, null);
        X = slaVar2;
        sla slaVar3 = new sla("RECONNECT", 2, (short) 3, null);
        Y = slaVar3;
        sla slaVar4 = new sla("LOG", 3, (short) 5, null);
        Z = slaVar4;
        sla slaVar5 = new sla("SESSION_INIT", 4, (short) 6, null);
        s0 = slaVar5;
        sla slaVar6 = new sla("PROFILE", 5, (short) 16, null);
        sla slaVar7 = new sla("AUTH_REQUEST", 6, (short) 17, null);
        t0 = slaVar7;
        sla slaVar8 = new sla("AUTH", 7, (short) 18, null);
        u0 = slaVar8;
        sla slaVar9 = new sla("LOGIN", 8, (short) 19, o84.Y);
        v0 = slaVar9;
        sla slaVar10 = new sla("LOGOUT", 9, (short) 20, null);
        w0 = slaVar10;
        sla slaVar11 = new sla("SYNC", 10, (short) 21, null);
        x0 = slaVar11;
        sla slaVar12 = new sla("CONFIG", 11, (short) 22, null);
        y0 = slaVar12;
        sla slaVar13 = new sla("AUTH_CONFIRM", 12, (short) 23, null);
        z0 = slaVar13;
        sla slaVar14 = new sla("ASSETS_GET", 13, (short) 26, null);
        A0 = slaVar14;
        sla slaVar15 = new sla("ASSETS_UPDATE", 14, (short) 27, null);
        B0 = slaVar15;
        sla slaVar16 = new sla("ASSETS_GET_BY_IDS", 15, (short) 28, null);
        C0 = slaVar16;
        sla slaVar17 = new sla("ASSETS_LIST_MODIFY", 16, (short) 261, null);
        D0 = slaVar17;
        sla slaVar18 = new sla("ASSETS_REMOVE", 17, (short) 259, null);
        E0 = slaVar18;
        sla slaVar19 = new sla("ASSETS_MOVE", 18, (short) 260, null);
        F0 = slaVar19;
        sla slaVar20 = new sla("ASSETS_ADD", 19, (short) 29, null);
        G0 = slaVar20;
        sla slaVar21 = new sla("SEARCH_FEEDBACK", 20, (short) 31, null);
        H0 = slaVar21;
        sla slaVar22 = new sla("PRESET_AVATARS", 21, (short) 25, rq9.t0);
        I0 = slaVar22;
        sla slaVar23 = new sla("CONTACT_INFO", 22, (short) 32, o84.o);
        J0 = slaVar23;
        sla slaVar24 = new sla("CONTACT_INFO_BY_PHONE", 23, (short) 46, sp3.b);
        K0 = slaVar24;
        sla slaVar25 = new sla("CONTACT_ADD", 24, (short) 33, null);
        sla slaVar26 = new sla("CONTACT_UPDATE", 25, (short) 34, null);
        sla slaVar27 = new sla("CONTACT_PRESENCE", 26, (short) 35, null);
        sla slaVar28 = new sla("CONTACT_LIST", 27, (short) 36, null);
        sla slaVar29 = new sla("CONTACT_SEARCH", 28, (short) 37, null);
        sla slaVar30 = new sla("CONTACT_MUTUAL", 29, (short) 38, null);
        sla slaVar31 = new sla("CONTACT_PHOTOS", 30, (short) 39, null);
        sla slaVar32 = new sla("CONTACT_SORT", 31, (short) 40, null);
        sla slaVar33 = new sla("CONTACT_VERIFY", 32, (short) 42, null);
        L0 = slaVar33;
        sla slaVar34 = new sla("REMOVE_CONTACT_PHOTO", 33, (short) 43, null);
        M0 = slaVar34;
        sla slaVar35 = new sla("CHAT_INFO", 34, (short) 48, null);
        sla slaVar36 = new sla("CHAT_HISTORY", 35, (short) 49, null);
        N0 = slaVar36;
        sla slaVar37 = new sla("CHAT_MARK", 36, (short) 50, oq9.c);
        O0 = slaVar37;
        sla slaVar38 = new sla("CHAT_MEDIA", 37, (short) 51, null);
        P0 = slaVar38;
        sla slaVar39 = new sla("CHAT_DELETE", 38, (short) 52, null);
        sla slaVar40 = new sla("CHATS_LIST", 39, (short) 53, null);
        Q0 = slaVar40;
        sla slaVar41 = new sla("CHAT_CLEAR", 40, (short) 54, null);
        sla slaVar42 = new sla("CHAT_UPDATE", 41, (short) 55, null);
        R0 = slaVar42;
        sla slaVar43 = new sla("CHAT_CHECK_LINK", 42, (short) 56, null);
        S0 = slaVar43;
        sla slaVar44 = new sla("CHAT_JOIN", 43, (short) 57, null);
        T0 = slaVar44;
        sla slaVar45 = new sla("CHAT_LEAVE", 44, (short) 58, null);
        U0 = slaVar45;
        sla slaVar46 = new sla("CHAT_MEMBERS", 45, (short) 59, null);
        V0 = slaVar46;
        sla slaVar47 = new sla("PUBLIC_SEARCH", 46, (short) 60, null);
        W0 = slaVar47;
        sla slaVar48 = new sla("CHAT_CLOSE", 47, (short) 61, null);
        X0 = slaVar48;
        sla slaVar49 = new sla("CHAT_CREATE", 48, (short) 63, null);
        Y0 = slaVar49;
        sla slaVar50 = new sla("MSG_SEND", 49, (short) 64, null);
        Z0 = slaVar50;
        sla slaVar51 = new sla("MSG_TYPING", 50, (short) 65, null);
        sla slaVar52 = new sla("MSG_DELETE", 51, (short) 66, null);
        a1 = slaVar52;
        sla slaVar53 = new sla("MSG_EDIT", 52, (short) 67, null);
        b1 = slaVar53;
        sla slaVar54 = new sla("MSG_DELETE_RANGE", 53, (short) 92, null);
        c1 = slaVar54;
        sla slaVar55 = new sla("MSG_REACTION", 54, (short) 178, null);
        sla slaVar56 = new sla("MSG_CANCEL_REACTION", 55, (short) 179, null);
        sla slaVar57 = new sla("MSG_GET_REACTIONS", 56, (short) 180, kj6.X);
        d1 = slaVar57;
        sla slaVar58 = new sla("MSG_GET_DETAILED_REACTIONS", 57, (short) 181, null);
        sla slaVar59 = new sla("CHAT_SEARCH", 58, (short) 68, null);
        e1 = slaVar59;
        sla slaVar60 = new sla("MSG_SHARE_PREVIEW", 59, (short) 70, null);
        f1 = slaVar60;
        sla slaVar61 = new sla("MSG_GET", 60, (short) 71, null);
        g1 = slaVar61;
        sla slaVar62 = new sla("MSG_SEARCH_TOUCH", 61, (short) 72, null);
        sla slaVar63 = new sla("MSG_SEARCH", 62, (short) 73, null);
        h1 = slaVar63;
        sla slaVar64 = new sla("MSG_GET_STAT", 63, (short) 74, null);
        i1 = slaVar64;
        sla slaVar65 = new sla("CHAT_SUBSCRIBE", 64, (short) 75, null);
        j1 = slaVar65;
        sla slaVar66 = new sla("VIDEO_CHAT_START", 65, (short) 76, null);
        k1 = slaVar66;
        sla slaVar67 = new sla("CHAT_MEMBERS_UPDATE", 66, (short) 77, null);
        l1 = slaVar67;
        sla slaVar68 = new sla("VIDEO_CHAT_HISTORY", 67, (short) 79, null);
        m1 = slaVar68;
        sla slaVar69 = new sla("PHOTO_UPLOAD", 68, (short) 80, null);
        sla slaVar70 = new sla("STICKER_UPLOAD", 69, (short) 81, null);
        n1 = slaVar70;
        sla slaVar71 = new sla("VIDEO_UPLOAD", 70, (short) 82, null);
        o1 = slaVar71;
        sla slaVar72 = new sla("VIDEO_PLAY", 71, (short) 83, null);
        p1 = slaVar72;
        sla slaVar73 = new sla("CHAT_PIN_SET_VISIBILITY", 72, (short) 86, null);
        q1 = slaVar73;
        sla slaVar74 = new sla("FILE_UPLOAD", 73, (short) 87, null);
        r1 = slaVar74;
        sla slaVar75 = new sla("FILE_DOWNLOAD", 74, (short) 88, null);
        s1 = slaVar75;
        sla slaVar76 = new sla("LINK_INFO", 75, (short) 89, null);
        t1 = slaVar76;
        sla slaVar77 = new sla("SESSIONS_INFO", 76, (short) 96, null);
        u1 = slaVar77;
        sla slaVar78 = new sla("SESSIONS_CLOSE", 77, (short) 97, null);
        v1 = slaVar78;
        sla slaVar79 = new sla("PHONE_BIND_REQUEST", 78, (short) 98, null);
        w1 = slaVar79;
        sla slaVar80 = new sla("PHONE_BIND_CONFIRM", 79, (short) 99, null);
        x1 = slaVar80;
        sla slaVar81 = new sla("CONFIRM_PRESENT", 80, (short) 101, null);
        y1 = slaVar81;
        sla slaVar82 = new sla("GET_INBOUND_CALLS", 81, (short) 103, null);
        z1 = slaVar82;
        sla slaVar83 = new sla("EXTERNAL_CALLBACK", 82, (short) 105, vu4.c);
        A1 = slaVar83;
        sla slaVar84 = new sla("CALLS_TOKEN", 83, (short) 158, null);
        B1 = slaVar84;
        sla slaVar85 = new sla("CHAT_COMPLAIN", 84, (short) 117, null);
        C1 = slaVar85;
        sla slaVar86 = new sla("MSG_SEND_CALLBACK", 85, (short) 118, null);
        D1 = slaVar86;
        sla slaVar87 = new sla("SUSPEND_BOT", 86, (short) 119, null);
        sla slaVar88 = new sla("LOCATION_STOP", 87, (short) 124, null);
        E1 = slaVar88;
        sla slaVar89 = new sla("LOCATION_SEND", 88, (short) 125, null);
        F1 = slaVar89;
        sla slaVar90 = new sla("LOCATION_REQUEST", 89, (short) 126, null);
        G1 = slaVar90;
        sla slaVar91 = new sla("GET_LAST_MENTIONS", 90, (short) 127, null);
        H1 = slaVar91;
        sla slaVar92 = new sla("STICKER_CREATE", 91, (short) 193, null);
        I1 = slaVar92;
        sla slaVar93 = new sla("STICKER_SUGGEST", 92, (short) 194, null);
        J1 = slaVar93;
        sla slaVar94 = new sla("VIDEO_CHAT_MEMBERS", 93, (short) 195, null);
        K1 = slaVar94;
        sla slaVar95 = new sla("NOTIF_MESSAGE", 94, (short) 128, is9.a);
        L1 = slaVar95;
        sla slaVar96 = new sla("NOTIF_TYPING", 95, (short) 129, null);
        M1 = slaVar96;
        sla slaVar97 = new sla("NOTIF_MARK", 96, (short) 130, mq9.Y);
        N1 = slaVar97;
        sla slaVar98 = new sla("NOTIF_CONTACT", 97, (short) 131, null);
        O1 = slaVar98;
        sla slaVar99 = new sla("NOTIF_PRESENCE", 98, (short) 132, null);
        P1 = slaVar99;
        sla slaVar100 = new sla("NOTIF_CONFIG", 99, (short) 134, null);
        Q1 = slaVar100;
        sla slaVar101 = new sla("NOTIF_CHAT", 100, (short) 135, null);
        R1 = slaVar101;
        sla slaVar102 = new sla("NOTIF_ATTACH", HttpStatus.SC_SWITCHING_PROTOCOLS, (short) 136, null);
        S1 = slaVar102;
        sla slaVar103 = new sla("NOTIF_CALL_START", HttpStatus.SC_PROCESSING, (short) 137, null);
        T1 = slaVar103;
        sla slaVar104 = new sla("NOTIF_CONTACT_SORT", 103, (short) 139, null);
        U1 = slaVar104;
        sla slaVar105 = new sla("NOTIF_MSG_DELETE_RANGE", 104, (short) 140, null);
        V1 = slaVar105;
        sla slaVar106 = new sla("NOTIF_MSG_DELETE", 105, (short) 142, pq9.v0);
        W1 = slaVar106;
        sla slaVar107 = new sla("NOTIF_MSG_REACTIONS_CHANGED", 106, (short) 155, null);
        X1 = slaVar107;
        sla slaVar108 = new sla("NOTIF_MSG_YOU_REACTED", 107, (short) 156, null);
        Y1 = slaVar108;
        sla slaVar109 = new sla("NOTIF_CALLBACK_ANSWER", 108, (short) 143, null);
        Z1 = slaVar109;
        sla slaVar110 = new sla("CHAT_BOT_COMMANDS", 109, (short) 144, null);
        a2 = slaVar110;
        sla slaVar111 = new sla("BOT_INFO", 110, (short) 145, qx7.b);
        b2 = slaVar111;
        sla slaVar112 = new sla("NOTIF_LOCATION", 111, (short) 147, null);
        c2 = slaVar112;
        sla slaVar113 = new sla("NOTIF_LOCATION_REQUEST", 112, (short) 148, null);
        d2 = slaVar113;
        sla slaVar114 = new sla("NOTIF_ASSETS_UPDATE", 113, (short) 150, null);
        e2 = slaVar114;
        sla slaVar115 = new sla("NOTIF_DRAFT", 114, (short) 152, null);
        f2 = slaVar115;
        sla slaVar116 = new sla("NOTIF_DRAFT_DISCARD", 115, (short) 153, null);
        g2 = slaVar116;
        sla slaVar117 = new sla("DRAFT_SAVE", 116, (short) 176, null);
        h2 = slaVar117;
        sla slaVar118 = new sla("DRAFT_DISCARD", 117, (short) 177, null);
        i2 = slaVar118;
        sla slaVar119 = new sla("CHAT_HIDE", 118, (short) 196, null);
        j2 = slaVar119;
        sla slaVar120 = new sla("CHAT_SEARCH_COMMON_PARTICIPANTS", 119, (short) 198, null);
        k2 = slaVar120;
        sla slaVar121 = new sla("NOTIF_MSG_DELAYED", 120, (short) 154, oq9.Y);
        l2 = slaVar121;
        sla slaVar122 = new sla("NOTIF_PROFILE", 121, (short) 159, qq9.u0);
        m2 = slaVar122;
        sla slaVar123 = new sla("PROFILE_DELETE", 122, (short) 199, b46.u0);
        n2 = slaVar123;
        sla slaVar124 = new sla("PROFILE_DELETE_TIME", 123, (short) 200, xxc.Y);
        o2 = slaVar124;
        sla slaVar125 = new sla("WEB_APP_INIT_DATA", 124, (short) 160, yxc.t0);
        p2 = slaVar125;
        sla[] slaVarArr = {slaVar, slaVar2, slaVar3, slaVar4, slaVar5, slaVar6, slaVar7, slaVar8, slaVar9, slaVar10, slaVar11, slaVar12, slaVar13, slaVar14, slaVar15, slaVar16, slaVar17, slaVar18, slaVar19, slaVar20, slaVar21, slaVar22, slaVar23, slaVar24, slaVar25, slaVar26, slaVar27, slaVar28, slaVar29, slaVar30, slaVar31, slaVar32, slaVar33, slaVar34, slaVar35, slaVar36, slaVar37, slaVar38, slaVar39, slaVar40, slaVar41, slaVar42, slaVar43, slaVar44, slaVar45, slaVar46, slaVar47, slaVar48, slaVar49, slaVar50, slaVar51, slaVar52, slaVar53, slaVar54, slaVar55, slaVar56, slaVar57, slaVar58, slaVar59, slaVar60, slaVar61, slaVar62, slaVar63, slaVar64, slaVar65, slaVar66, slaVar67, slaVar68, slaVar69, slaVar70, slaVar71, slaVar72, slaVar73, slaVar74, slaVar75, slaVar76, slaVar77, slaVar78, slaVar79, slaVar80, slaVar81, slaVar82, slaVar83, slaVar84, slaVar85, slaVar86, slaVar87, slaVar88, slaVar89, slaVar90, slaVar91, slaVar92, slaVar93, slaVar94, slaVar95, slaVar96, slaVar97, slaVar98, slaVar99, slaVar100, slaVar101, slaVar102, slaVar103, slaVar104, slaVar105, slaVar106, slaVar107, slaVar108, slaVar109, slaVar110, slaVar111, slaVar112, slaVar113, slaVar114, slaVar115, slaVar116, slaVar117, slaVar118, slaVar119, slaVar120, slaVar121, slaVar122, slaVar123, slaVar124, slaVar125};
        q2 = slaVarArr;
        v25 v25Var = new v25(slaVarArr);
        c = new yb9();
        o = new HashMap();
        u1 u1Var = new u1(0, v25Var);
        while (u1Var.hasNext()) {
            sla slaVar126 = (sla) u1Var.next();
            o.put(Short.valueOf(slaVar126.a), slaVar126.name());
        }
    }

    public sla(String str, int i, short s, s43 s43Var) {
        this.a = s;
        this.b = s43Var;
    }

    public static final String b(short s) {
        c.getClass();
        HashMap map = o;
        Short shValueOf = Short.valueOf(s);
        Object objC = map.get(shValueOf);
        if (objC == null) {
            objC = yb9.c(s);
            map.put(shValueOf, objC);
        }
        return (String) objC;
    }

    public static sla valueOf(String str) {
        return (sla) Enum.valueOf(sla.class, str);
    }

    public static sla[] values() {
        return (sla[]) q2.clone();
    }

    public final s43 a() {
        return this.b;
    }

    public final short c() {
        return this.a;
    }
}
