package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* loaded from: classes.dex */
public final class yi3 {
    public int a;
    public final bj3 b;
    public final aj3 c;
    public final zi3 d;
    public final cj3 e;
    public HashMap f;

    public yi3() {
        bj3 bj3Var = new bj3();
        bj3Var.a = 0;
        bj3Var.b = 0;
        bj3Var.c = 1.0f;
        bj3Var.d = Float.NaN;
        this.b = bj3Var;
        aj3 aj3Var = new aj3();
        aj3Var.a = -1;
        aj3Var.b = 0;
        aj3Var.c = -1;
        aj3Var.d = Float.NaN;
        aj3Var.e = Float.NaN;
        aj3Var.f = Float.NaN;
        aj3Var.g = -1;
        aj3Var.h = null;
        aj3Var.i = -1;
        this.c = aj3Var;
        zi3 zi3Var = new zi3();
        zi3Var.a = false;
        zi3Var.d = -1;
        zi3Var.e = -1;
        zi3Var.f = -1.0f;
        zi3Var.g = true;
        zi3Var.h = -1;
        zi3Var.i = -1;
        zi3Var.j = -1;
        zi3Var.k = -1;
        zi3Var.l = -1;
        zi3Var.m = -1;
        zi3Var.n = -1;
        zi3Var.o = -1;
        zi3Var.p = -1;
        zi3Var.q = -1;
        zi3Var.r = -1;
        zi3Var.s = -1;
        zi3Var.t = -1;
        zi3Var.u = -1;
        zi3Var.v = -1;
        zi3Var.w = 0.5f;
        zi3Var.x = 0.5f;
        zi3Var.y = null;
        zi3Var.z = -1;
        zi3Var.A = 0;
        zi3Var.B = 0.0f;
        zi3Var.C = -1;
        zi3Var.D = -1;
        zi3Var.E = -1;
        zi3Var.F = 0;
        zi3Var.G = 0;
        zi3Var.H = 0;
        zi3Var.I = 0;
        zi3Var.J = 0;
        zi3Var.K = 0;
        zi3Var.L = 0;
        zi3Var.M = Integer.MIN_VALUE;
        zi3Var.N = Integer.MIN_VALUE;
        zi3Var.O = Integer.MIN_VALUE;
        zi3Var.P = Integer.MIN_VALUE;
        zi3Var.Q = Integer.MIN_VALUE;
        zi3Var.R = Integer.MIN_VALUE;
        zi3Var.S = Integer.MIN_VALUE;
        zi3Var.T = -1.0f;
        zi3Var.U = -1.0f;
        zi3Var.V = 0;
        zi3Var.W = 0;
        zi3Var.X = 0;
        zi3Var.Y = 0;
        zi3Var.Z = 0;
        zi3Var.a0 = 0;
        zi3Var.b0 = 0;
        zi3Var.c0 = 0;
        zi3Var.d0 = 1.0f;
        zi3Var.e0 = 1.0f;
        zi3Var.f0 = -1;
        zi3Var.g0 = 0;
        zi3Var.h0 = -1;
        zi3Var.l0 = false;
        zi3Var.m0 = false;
        zi3Var.n0 = true;
        zi3Var.o0 = 0;
        this.d = zi3Var;
        cj3 cj3Var = new cj3();
        cj3Var.a = 0.0f;
        cj3Var.b = 0.0f;
        cj3Var.c = 0.0f;
        cj3Var.d = 1.0f;
        cj3Var.e = 1.0f;
        cj3Var.f = Float.NaN;
        cj3Var.g = Float.NaN;
        cj3Var.h = -1;
        cj3Var.i = 0.0f;
        cj3Var.j = 0.0f;
        cj3Var.k = 0.0f;
        cj3Var.l = false;
        cj3Var.m = 0.0f;
        this.e = cj3Var;
        this.f = new HashMap();
    }

    public final void a(ti3 ti3Var) {
        zi3 zi3Var = this.d;
        ti3Var.e = zi3Var.h;
        ti3Var.f = zi3Var.i;
        ti3Var.g = zi3Var.j;
        ti3Var.h = zi3Var.k;
        ti3Var.i = zi3Var.l;
        ti3Var.j = zi3Var.m;
        ti3Var.k = zi3Var.n;
        ti3Var.l = zi3Var.o;
        ti3Var.m = zi3Var.p;
        ti3Var.n = zi3Var.q;
        ti3Var.o = zi3Var.r;
        ti3Var.s = zi3Var.s;
        ti3Var.t = zi3Var.t;
        ti3Var.u = zi3Var.u;
        ti3Var.v = zi3Var.v;
        ((ViewGroup.MarginLayoutParams) ti3Var).leftMargin = zi3Var.F;
        ((ViewGroup.MarginLayoutParams) ti3Var).rightMargin = zi3Var.G;
        ((ViewGroup.MarginLayoutParams) ti3Var).topMargin = zi3Var.H;
        ((ViewGroup.MarginLayoutParams) ti3Var).bottomMargin = zi3Var.I;
        ti3Var.A = zi3Var.R;
        ti3Var.B = zi3Var.Q;
        ti3Var.x = zi3Var.N;
        ti3Var.z = zi3Var.P;
        ti3Var.E = zi3Var.w;
        ti3Var.F = zi3Var.x;
        ti3Var.p = zi3Var.z;
        ti3Var.q = zi3Var.A;
        ti3Var.r = zi3Var.B;
        ti3Var.G = zi3Var.y;
        ti3Var.T = zi3Var.C;
        ti3Var.U = zi3Var.D;
        ti3Var.I = zi3Var.T;
        ti3Var.H = zi3Var.U;
        ti3Var.K = zi3Var.W;
        ti3Var.J = zi3Var.V;
        ti3Var.W = zi3Var.l0;
        ti3Var.X = zi3Var.m0;
        ti3Var.L = zi3Var.X;
        ti3Var.M = zi3Var.Y;
        ti3Var.P = zi3Var.Z;
        ti3Var.Q = zi3Var.a0;
        ti3Var.N = zi3Var.b0;
        ti3Var.O = zi3Var.c0;
        ti3Var.R = zi3Var.d0;
        ti3Var.S = zi3Var.e0;
        ti3Var.V = zi3Var.E;
        ti3Var.c = zi3Var.f;
        ti3Var.a = zi3Var.d;
        ti3Var.b = zi3Var.e;
        ((ViewGroup.MarginLayoutParams) ti3Var).width = zi3Var.b;
        ((ViewGroup.MarginLayoutParams) ti3Var).height = zi3Var.c;
        String str = zi3Var.k0;
        if (str != null) {
            ti3Var.Y = str;
        }
        ti3Var.Z = zi3Var.o0;
        ti3Var.setMarginStart(zi3Var.K);
        ti3Var.setMarginEnd(zi3Var.J);
        ti3Var.a();
    }

    public final Object clone() {
        yi3 yi3Var = new yi3();
        zi3 zi3Var = yi3Var.d;
        zi3Var.getClass();
        zi3 zi3Var2 = this.d;
        zi3Var.a = zi3Var2.a;
        zi3Var.b = zi3Var2.b;
        zi3Var.c = zi3Var2.c;
        zi3Var.d = zi3Var2.d;
        zi3Var.e = zi3Var2.e;
        zi3Var.f = zi3Var2.f;
        zi3Var.g = zi3Var2.g;
        zi3Var.h = zi3Var2.h;
        zi3Var.i = zi3Var2.i;
        zi3Var.j = zi3Var2.j;
        zi3Var.k = zi3Var2.k;
        zi3Var.l = zi3Var2.l;
        zi3Var.m = zi3Var2.m;
        zi3Var.n = zi3Var2.n;
        zi3Var.o = zi3Var2.o;
        zi3Var.p = zi3Var2.p;
        zi3Var.q = zi3Var2.q;
        zi3Var.r = zi3Var2.r;
        zi3Var.s = zi3Var2.s;
        zi3Var.t = zi3Var2.t;
        zi3Var.u = zi3Var2.u;
        zi3Var.v = zi3Var2.v;
        zi3Var.w = zi3Var2.w;
        zi3Var.x = zi3Var2.x;
        zi3Var.y = zi3Var2.y;
        zi3Var.z = zi3Var2.z;
        zi3Var.A = zi3Var2.A;
        zi3Var.B = zi3Var2.B;
        zi3Var.C = zi3Var2.C;
        zi3Var.D = zi3Var2.D;
        zi3Var.E = zi3Var2.E;
        zi3Var.F = zi3Var2.F;
        zi3Var.G = zi3Var2.G;
        zi3Var.H = zi3Var2.H;
        zi3Var.I = zi3Var2.I;
        zi3Var.J = zi3Var2.J;
        zi3Var.K = zi3Var2.K;
        zi3Var.L = zi3Var2.L;
        zi3Var.M = zi3Var2.M;
        zi3Var.N = zi3Var2.N;
        zi3Var.O = zi3Var2.O;
        zi3Var.P = zi3Var2.P;
        zi3Var.Q = zi3Var2.Q;
        zi3Var.R = zi3Var2.R;
        zi3Var.S = zi3Var2.S;
        zi3Var.T = zi3Var2.T;
        zi3Var.U = zi3Var2.U;
        zi3Var.V = zi3Var2.V;
        zi3Var.W = zi3Var2.W;
        zi3Var.X = zi3Var2.X;
        zi3Var.Y = zi3Var2.Y;
        zi3Var.Z = zi3Var2.Z;
        zi3Var.a0 = zi3Var2.a0;
        zi3Var.b0 = zi3Var2.b0;
        zi3Var.c0 = zi3Var2.c0;
        zi3Var.d0 = zi3Var2.d0;
        zi3Var.e0 = zi3Var2.e0;
        zi3Var.f0 = zi3Var2.f0;
        zi3Var.g0 = zi3Var2.g0;
        zi3Var.h0 = zi3Var2.h0;
        zi3Var.k0 = zi3Var2.k0;
        int[] iArr = zi3Var2.i0;
        if (iArr == null || zi3Var2.j0 != null) {
            zi3Var.i0 = null;
        } else {
            zi3Var.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        zi3Var.j0 = zi3Var2.j0;
        zi3Var.l0 = zi3Var2.l0;
        zi3Var.m0 = zi3Var2.m0;
        zi3Var.n0 = zi3Var2.n0;
        zi3Var.o0 = zi3Var2.o0;
        aj3 aj3Var = yi3Var.c;
        aj3Var.getClass();
        aj3 aj3Var2 = this.c;
        aj3Var2.getClass();
        aj3Var.a = aj3Var2.a;
        aj3Var.c = aj3Var2.c;
        aj3Var.e = aj3Var2.e;
        aj3Var.d = aj3Var2.d;
        bj3 bj3Var = yi3Var.b;
        bj3Var.getClass();
        bj3 bj3Var2 = this.b;
        bj3Var2.getClass();
        bj3Var.a = bj3Var2.a;
        bj3Var.c = bj3Var2.c;
        bj3Var.d = bj3Var2.d;
        bj3Var.b = bj3Var2.b;
        cj3 cj3Var = yi3Var.e;
        cj3Var.getClass();
        cj3 cj3Var2 = this.e;
        cj3Var2.getClass();
        cj3Var.a = cj3Var2.a;
        cj3Var.b = cj3Var2.b;
        cj3Var.c = cj3Var2.c;
        cj3Var.d = cj3Var2.d;
        cj3Var.e = cj3Var2.e;
        cj3Var.f = cj3Var2.f;
        cj3Var.g = cj3Var2.g;
        cj3Var.h = cj3Var2.h;
        cj3Var.i = cj3Var2.i;
        cj3Var.j = cj3Var2.j;
        cj3Var.k = cj3Var2.k;
        cj3Var.l = cj3Var2.l;
        cj3Var.m = cj3Var2.m;
        yi3Var.a = this.a;
        return yi3Var;
    }
}
