package com.google.android.material;

import defpackage.jyb;

/* loaded from: classes.dex */
public final class ComGoogleAndroidMaterialR$integer {
    public static final int abc_config_activityDefaultDur = jyb.abc_config_activityDefaultDur;
    public static final int abc_config_activityShortDur = jyb.abc_config_activityShortDur;
    public static final int app_bar_elevation_anim_duration = jyb.app_bar_elevation_anim_duration;
    public static final int bottom_sheet_slide_duration = jyb.bottom_sheet_slide_duration;
    public static final int cancel_button_image_alpha = jyb.cancel_button_image_alpha;
    public static final int config_tooltipAnimTime = jyb.config_tooltipAnimTime;
    public static final int design_snackbar_text_max_lines = jyb.design_snackbar_text_max_lines;
    public static final int design_tab_indicator_anim_duration_ms = jyb.design_tab_indicator_anim_duration_ms;
    public static final int hide_password_duration = jyb.hide_password_duration;
    public static final int m3_badge_max_number = jyb.m3_badge_max_number;
    public static final int m3_btn_anim_delay_ms = jyb.m3_btn_anim_delay_ms;
    public static final int m3_btn_anim_duration_ms = jyb.m3_btn_anim_duration_ms;
    public static final int m3_card_anim_delay_ms = jyb.m3_card_anim_delay_ms;
    public static final int m3_card_anim_duration_ms = jyb.m3_card_anim_duration_ms;
    public static final int m3_chip_anim_duration = jyb.m3_chip_anim_duration;
    public static final int m3_sys_motion_duration_extra_long1 = jyb.m3_sys_motion_duration_extra_long1;
    public static final int m3_sys_motion_duration_extra_long2 = jyb.m3_sys_motion_duration_extra_long2;
    public static final int m3_sys_motion_duration_extra_long3 = jyb.m3_sys_motion_duration_extra_long3;
    public static final int m3_sys_motion_duration_extra_long4 = jyb.m3_sys_motion_duration_extra_long4;
    public static final int m3_sys_motion_duration_long1 = jyb.m3_sys_motion_duration_long1;
    public static final int m3_sys_motion_duration_long2 = jyb.m3_sys_motion_duration_long2;
    public static final int m3_sys_motion_duration_long3 = jyb.m3_sys_motion_duration_long3;
    public static final int m3_sys_motion_duration_long4 = jyb.m3_sys_motion_duration_long4;
    public static final int m3_sys_motion_duration_medium1 = jyb.m3_sys_motion_duration_medium1;
    public static final int m3_sys_motion_duration_medium2 = jyb.m3_sys_motion_duration_medium2;
    public static final int m3_sys_motion_duration_medium3 = jyb.m3_sys_motion_duration_medium3;
    public static final int m3_sys_motion_duration_medium4 = jyb.m3_sys_motion_duration_medium4;
    public static final int m3_sys_motion_duration_short1 = jyb.m3_sys_motion_duration_short1;
    public static final int m3_sys_motion_duration_short2 = jyb.m3_sys_motion_duration_short2;
    public static final int m3_sys_motion_duration_short3 = jyb.m3_sys_motion_duration_short3;
    public static final int m3_sys_motion_duration_short4 = jyb.m3_sys_motion_duration_short4;
    public static final int m3_sys_motion_path = jyb.m3_sys_motion_path;
    public static final int m3_sys_shape_corner_extra_large_corner_family = jyb.m3_sys_shape_corner_extra_large_corner_family;
    public static final int m3_sys_shape_corner_extra_small_corner_family = jyb.m3_sys_shape_corner_extra_small_corner_family;
    public static final int m3_sys_shape_corner_full_corner_family = jyb.m3_sys_shape_corner_full_corner_family;
    public static final int m3_sys_shape_corner_large_corner_family = jyb.m3_sys_shape_corner_large_corner_family;
    public static final int m3_sys_shape_corner_medium_corner_family = jyb.m3_sys_shape_corner_medium_corner_family;
    public static final int m3_sys_shape_corner_small_corner_family = jyb.m3_sys_shape_corner_small_corner_family;
    public static final int material_motion_duration_long_1 = jyb.material_motion_duration_long_1;
    public static final int material_motion_duration_long_2 = jyb.material_motion_duration_long_2;
    public static final int material_motion_duration_medium_1 = jyb.material_motion_duration_medium_1;
    public static final int material_motion_duration_medium_2 = jyb.material_motion_duration_medium_2;
    public static final int material_motion_duration_short_1 = jyb.material_motion_duration_short_1;
    public static final int material_motion_duration_short_2 = jyb.material_motion_duration_short_2;
    public static final int material_motion_path = jyb.material_motion_path;
    public static final int mtrl_badge_max_character_count = jyb.mtrl_badge_max_character_count;
    public static final int mtrl_btn_anim_delay_ms = jyb.mtrl_btn_anim_delay_ms;
    public static final int mtrl_btn_anim_duration_ms = jyb.mtrl_btn_anim_duration_ms;
    public static final int mtrl_calendar_header_orientation = jyb.mtrl_calendar_header_orientation;
    public static final int mtrl_calendar_selection_text_lines = jyb.mtrl_calendar_selection_text_lines;
    public static final int mtrl_calendar_year_selector_span = jyb.mtrl_calendar_year_selector_span;
    public static final int mtrl_card_anim_delay_ms = jyb.mtrl_card_anim_delay_ms;
    public static final int mtrl_card_anim_duration_ms = jyb.mtrl_card_anim_duration_ms;
    public static final int mtrl_chip_anim_duration = jyb.mtrl_chip_anim_duration;
    public static final int mtrl_switch_thumb_motion_duration = jyb.mtrl_switch_thumb_motion_duration;
    public static final int mtrl_switch_thumb_post_morphing_duration = jyb.mtrl_switch_thumb_post_morphing_duration;
    public static final int mtrl_switch_thumb_pre_morphing_duration = jyb.mtrl_switch_thumb_pre_morphing_duration;
    public static final int mtrl_switch_thumb_pressed_duration = jyb.mtrl_switch_thumb_pressed_duration;
    public static final int mtrl_switch_thumb_viewport_center_coordinate = jyb.mtrl_switch_thumb_viewport_center_coordinate;
    public static final int mtrl_switch_thumb_viewport_size = jyb.mtrl_switch_thumb_viewport_size;
    public static final int mtrl_switch_track_viewport_height = jyb.mtrl_switch_track_viewport_height;
    public static final int mtrl_switch_track_viewport_width = jyb.mtrl_switch_track_viewport_width;
    public static final int mtrl_tab_indicator_anim_duration_ms = jyb.mtrl_tab_indicator_anim_duration_ms;
    public static final int mtrl_view_gone = jyb.mtrl_view_gone;
    public static final int mtrl_view_invisible = jyb.mtrl_view_invisible;
    public static final int mtrl_view_visible = jyb.mtrl_view_visible;
    public static final int show_password_duration = jyb.show_password_duration;
    public static final int status_bar_notification_info_maxnum = jyb.status_bar_notification_info_maxnum;
}
